SELECT ANIMAL_INS.ANIMAL_ID,
       ANIMAL_INS.NAME
  FROM ANIMAL_INS
  JOIN ANIMAL_OUTS
 WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
   AND ANIMAL_OUTS.DATETIME < ANIMAL_INS.DATETIME
 ORDER BY ANIMAL_INS.DATETIME ASC;
