SELECT A.ANIMAL_ID, A.NAME
  FROM (SELECT OUTS.ANIMAL_ID, OUTS.NAME, DATEDIFF(OUTS.DATETIME, INS.DATETIME) AS DATE
          FROM ANIMAL_OUTS AS OUTS , ANIMAL_INS AS INS
         WHERE OUTS.ANIMAL_ID = INS.ANIMAL_ID)AS A
 ORDER BY DATE DESC LIMIT 2;
