# 자동차 매출 데이터(CLASSICMODELS)를 이용한 리포트 작성

# 1. 구매 지표 추출

#  1) 매출액(익자별, 월별, 연도별)

#   A) 일별 매출액 조회
# CLASSICMODELS.ORDERS 테이블의 주문 정보에 ORDERDETAILS의 주문 상품 가격 결합 후, ORDERDATE와 PRICEEACH * QUANTITYORDERED(매출액)를 조회
SELECT A.ORDERDATE,
	   PRICEEACH * QUANTITYORDERED
  FROM CLASSICMODELS.ORDERS A
  LEFT
  JOIN CLASSICMODELS.ORDERDETAILS B
    ON A.ORDERNUMBER = B.ORDERNUMBER;
    
# ORDERDATE로 그룹핑한 뒤, PRICEEACH * QUANTITYORDERED(매출액)의 합을 집계
SELECT A.ORDERDATE,
	   SUM(PRICEEACH * QUANTITYORDERED) AS SALES
  FROM CLASSICMODELS.ORDERS A
  LEFT
  JOIN CLASSICMODELS.ORDERDETAILS B
    ON A.ORDERNUMBER = B.ORDERNUMBER
 GROUP BY 1
 ORDER BY 1;
 
 #   B) 월별 매출액 조회
 # 위와 동일한 방법을 취하되, SUBSTR()을 이용하여 'YYYY-MM'까지의 정보만 가져와서 조회
SELECT SUBSTR(A.ORDERDATE,1,7) MM,
	   SUM(PRICEEACH * QUANTITYORDERED) AS SALES
  FROM CLASSICMODELS.ORDERS A
  LEFT
  JOIN CLASSICMODELS.ORDERDETAILS B
    ON A.ORDERNUMBER = B.ORDERNUMBER
 GROUP BY 1
 ORDER BY 1;
 
#   C) 연도별 매출액 조회
# 위와 동일한 방법을 취하되, SUBSTR()을 이용하여 'YYYY'정보만 가져와서 조회
SELECT SUBSTR(A.ORDERDATE,1,4) YYYY,
	   SUM(PRICEEACH * QUANTITYORDERED) AS SALES
  FROM CLASSICMODELS.ORDERS A
  LEFT
  JOIN CLASSICMODELS.ORDERDETAILS B
    ON A.ORDERNUMBER = B.ORDERNUMBER
 GROUP BY 1
 ORDER BY 1;
 
#  2) 구매자 수, 구매 건수(일자별, 월별, 연도별)
# ORDERDATE로 그루핑한 후 고객 번호를 COUNT (구매자 수, 구매 건수를 산출할 때는 보통 UNIQUE하게 필드를 COUNT해줘야 함)
# 일자별
SELECT ORDERDATE,
	   COUNT(DISTINCT CUSTOMERNUMBER) N_PURCHASER,
       COUNT(ORDERNUMBER) N_ORDERS
  FROM CLASSICMODELS.ORDERS
 GROUP BY 1
 ORDER BY 1;
 
# 월별
SELECT SUBSTR(ORDERDATE,1,7) MM,
	   COUNT(DISTINCT CUSTOMERNUMBER) N_PURCHASER,
	   COUNT(ORDERNUMBER) N_ORDERS
  FROM CLASSICMODELS.ORDERS
 GROUP BY 1
 ORDER BY 1;
 
#연도별
SELECT SUBSTR(ORDERDATE,1,4) YYYY,
	   COUNT(DISTINCT CUSTOMERNUMBER) N_PURCHASER,
	   COUNT(ORDERNUMBER) N_ORDERS
  FROM CLASSICMODELS.ORDERS
 GROUP BY 1
 ORDER BY 1;
 
#  3) 인당 매출액(연도별)
# 연도별 매출액과 구매자 수 구하기
SELECT SUBSTR(A.ORDERDATE,1,4) YYYY,
	   COUNT(DISTINCT A.CUSTOMERNUMBER) N_PURCHASER,
       SUM(PRICEEACH * QUANTITYORDERED) AS SALES
  FROM CLASSICMODELS.ORDERS A
  LEFT
  JOIN CLASSICMODELS.ORDERDETAILS B
    ON A.ORDERNUMBER = B.ORDERNUMBER
 GROUP BY 1
 ORDER BY 1;
 
 # 매출액을 구매자 수로 나누기
 SELECT SUBSTR(A.ORDERDATE,1,4) YYYY,
	    COUNT(DISTINCT A.CUSTOMERNUMBER) N_PURCHASER,
        SUM(PRICEEACH * QUANTITYORDERED) AS SALES,
        SUM(PRICEEACH * QUANTITYORDERED) / COUNT(DISTINCT A.CUSTOMERNUMBER) AMV
  FROM CLASSICMODELS.ORDERS A
  LEFT
  JOIN CLASSICMODELS.ORDERDETAILS B
    ON A.ORDERNUMBER = B.ORDERNUMBER
 GROUP BY 1
 ORDER BY 1;
 
#  4) 건당 구매 금액(ATV, Average Transaction Value)(연도별)
# 인당 구매 금액을 구하는 방법과 유사하지만, 매출을 구매자 수가 아닌 '구매 건수'로 나눔
SELECT SUBSTR(A.ORDERDATE,1,4) YYYY,
	   COUNT(DISTINCT A.ORDERNUMBER) N_PURCHASER,
       SUM(PRICEEACH * QUANTITYORDERED) AS SALES,
       SUM(PRICEEACH * QUANTITYORDERED) / COUNT(DISTINCT A.ORDERNUMBER) ATV
  FROM CLASSICMODELS.ORDERS A
  LEFT
  JOIN CLASSICMODELS.ORDERDETAILS B
    ON A.ORDERNUMBER = B.ORDERNUMBER
 GROUP BY 1
 ORDER BY 1;
 