# CLASSICMODELS.CUSTOMERS 테이블을 이용해 국가, 도시별 고객 수 구하기
SELECT COUNTRY, CITY, COUNT(CUSTOMERNUMBER) N_CUSTOMER
  FROM CLASSICMODELS.CUSTOMERS
 GROUP BY COUNTRY, CITY;
 
# CLASSICMODELS.CUSTOMERS 테이블을 이용해 USA 거주자의 수를 계산하고, 그 비중 구하기
SELECT SUM(CASE WHEN COUNTRY='USA' THEN 1 ELSE 0 END) N_USA,
	   SUM(CASE WHEN COUNTRY='USA' THEN 1 ELSE 0 END)/COUNT(*) USA_PORTION
  FROM CLASSICMODELS.CUSTOMERS;

# LETF JOIN은 FROM절의 테이블을 기준으로 매칭되는 정보를 호출
# CLASSICMODELS.ORDERS, CLASSICMODELS.CUSTOMERS 테이블을 결합하고 ORDERNUMBER와 COUNTRY 출력
SELECT A.ORDERNUMBER, B.COUNTRY
  FROM CLASSICMODELS.ORDERS A
  LEFT
  JOIN CLASSICMODELS.CUSTOMERS B
    ON A.CUSTOMERNUMBER = B.CUSTOMERNUMBER;
    
# INNER JOIN은 2가지 테이블에 공통으로 존재하는 값만 출력
# CLASSICMODELS.ORDERS, CLASSICMODELS.CUSTOMERS 테이블을 이용해 USA 거주자의 주문 번호(ORDERNUMBER), 국가(COUNTRY) 출력
SELECT A.ORDERNUMBER, B.COUNTRY
  FROM CLASSICMODELS.ORDERS A
 INNER
  JOIN CLASSICMODELS.CUSTOMERS B
    ON A.CUSTOMERNUMBER = B.CUSTOMERNUMBER
 WHERE B.COUNTRY='USA';
 
# FULL JOIN은 TABLE_A 또는 TABLE_B와 매칭되는 레코드를 모둧 출력함 →매우 큰 데이터 세트가 될 수 있음

# CLASSICMODELS.CUSTOMERS 의 COUNTRY 칼럼을 이용해 북미/비북미 출력
SELECT COUNTRY,
	   CASE WHEN COUNTRY IN ('USA', 'CANADA') THEN 'NORTH AMERICA' ELSE 'OTHERS' END AS REGION
  FROM CLASSICMODELS.CUSTOMERS;
  
# CLASSICMODELS.CUSTOMERS의 COUNTRY 칼럼을 이용해 북미/비북미를 출력하는 칼럼을 생성하고, 북미/비북미 거주 고객의 수를 계산
SELECT CASE WHEN COUNTRY IN ('USA', 'CANADA') THEN 'NORTH AMERICA' ELSE 'OTHERS' END AS REGION,
	   COUNT(CUSTOMERNUMBER) N_CUSTOMERS
  FROM CLASSICMODELS.CUSTOMERS
 GROUP BY 1;

