# ROW_NUMBER()는 동점인 경우도 서로 다른 등수로 계산
# RANK()는 동점인 경우의 데이터 세트를 고려해 다음 등수를 매김
# DENSE_RANK()는 동점의 등수 바로 다음 수로 순위를 매김

# CLASSICMODELS.PRODUCTS 테이블에서 BUYPRICE 칼럼으로 순위 매기기(오름차순)
SELECT BUYPRICE,
	   ROW_NUMBER() OVER(ORDER BY BUYPRICE) ROWNUMBER,
       RANK() OVER(ORDER BY BUYPRICE) CRNK,
       DENSE_RANK() OVER(ORDER BY BUYPRICE) DENSERANK
  FROM CLASSICMODELS.PRODUCTS;
  
# CLASSICMODELS.PRODUCTS 테이블의 PRODUCTLINE별로 순위 매기기(BUYPRICE 칼럼 기준, 오름차순)
SELECT BUYPRICE,
	   ROW_NUMBER() OVER(PARTITION BY PRODUCTLINE ORDER BY BUYPRICE) ROWNUMBER,
       RANK() OVER(PARTITION BY PRODUCTLINE ORDER BY BUYPRICE) RNK,
       DENSE_RANK() OVER(PARTITION BY PRODUCTLINE ORDER BY BUYPRICE) DENSERANK
  FROM CLASSICMODELS.PRODUCTS;