# CLASSICMODELS.CUSTOMERS의 CUSTOMERNUMBER 조회
SELECT CUSTOMERNUMBER
  FROM CLASSICMODELS.CUSTOMERS ;
  
# CLASSICMODELS.PRODUCTS의 PRODUCTNAME, PRODUCTLINE 조회
SELECT PRODUCTNAME, PRODUCTLINE
  FROM CLASSICMODELS.PRODUCTS;

# CLASSICMODELS.PAYMENTS의 AMOUNT의 총합과 CHECKNUMBER의 개수구하기
SELECT SUM(AMOUNT), COUNT(CHECKNUMBER)
  FROM CLASSICMODELS.PAYMENTS;
  
# CLASSICMODELS.PRODUCTS의 PRODUCTCODE의 개수를 구하고, 칼럼 명을 N_PRODUCTS로 변경
SELECT COUNT(PRODUCTCODE) AS N_PRODUCTS, COUNT(PRODUCTCODE) N_PRODUCTS
  FROM CLASSICMODELS.PRODUCTS;

# CLASSICMODELS.ORDERDETAILS의 ORDERNUMBER의 중복을 제거하고 조회
SELECT DISTINCT ORDERNUMBER
  FROM CLASSICMODELS.ORDERDETAILS;
