# 1. 요인별 생존 여부 관계
#  1) 성별
# PassengerId를 카운트해서 승객 수 집계하기
# PassengerId에 중복이 존재하는지 확인
SELECT COUNT(PASSENGERID) N_PASSENGERS,
       COUNT(DISTINCT PASSENGERID) N_D_PASSENGERS
  FROM MYDATA.DATASET4;
# PassengerId에 중복 존재하지 않음
  
# 성별에 따른 승객 수와 생존자 수 구하기
# Survived(생존 여부)에서 1은 생존, 0은 사망을 의미하므로, Survived의 합을 구하면 생존자의 수를 계산할 수 있음
SELECT SEX,
       COUNT(PASSENGERID) N_PASSENGERS,
       SUM(SURVIVED) N_SURVIVED
  FROM MYDATA.DATASET4
 GROUP BY 1;

# 성별 탑승객 수와 생존자 수 비중 구하기
SELECT SEX,
       COUNT(PASSENGERID) N_PASSENGERS,
	   SUM(SURVIVED) N_SURVIVED,
       SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATIO
  FROM MYDATA.DATASET4
 GROUP BY 1;
# 남성이 여성보다 더 많이 탑승했고, 생존율은 여성이 남성보다 약 55% 높았음

#  2) 연령, 성별
# 연령별로 탑승객 수와 생존자 수, 생존율 구하기
SELECT FLOOR(AGE/10)*10 AGEBAND,
       COUNT(PASSENGERID) N_PASSENGERS,
       SUM(SURVIVED) N_SURVIVED,
       SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
  FROM MYDATA.DATASET4
 GROUP BY 1;
 
# 연령대로 오름차순 정렬하기
SELECT FLOOR(AGE/10)*10 AGEBAND,
       COUNT(PASSENGERID) N_PASSENGERS,
       SUM(SURVIVED) N_SURVIVED,
       SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
  FROM MYDATA.DATASET4
 GROUP BY 1
 ORDER BY 1;
# 20대 탑승객이 가장 많고, 70대를 제외하면 60대의 생존율이 가장 낮음
# 생존율이 가장 높았던 그룹은 0~9세 아동으로 나타남

# 연령에 성별을 추가해서 생존율 파악하기
SELECT FLOOR(AGE/10)*10 AGEBAND,
       SEX,
       COUNT(PASSENGERID) N_PASSENGERS,
       SUM(SURVIVED) N_SURVIVED,
       SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
  FROM MYDATA.DATASET4
 GROUP BY 1, 2
 ORDER BY 2, 1;
# 50대 여성의 생존율이 가장 높게 나타나고, 10대 남성의 생존율이 가장 낮게 나타남(70대 제외)

# 남성, 여성의 동일 연령대별 생존율 차이 비교하기
SELECT A.AGEBAND,
       A.SURVIVED_RATE MALE_SURVIVED_RATE,
       B.SURVIVED_RATE FEMALE_SURVIVED_RATE,
       B.SURVIVED_RATE-A.SURVIVED_RATE SURVIVED_RATE_DIFF
  FROM (SELECT FLOOR(AGE/10)*10 AGEBAND,
               SEX,
               COUNT(PASSENGERID) N_PASSENGERS,
               SUM(SURVIVED) N_SURVIVED,
               SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
	  FROM MYDATA.DATASET4
	 GROUP BY 1, 2
	HAVING SEX='male') A
  LEFT
  JOIN (SELECT FLOOR(AGE/10)*10 AGEBAND,
               SEX,
               COUNT(PASSENGERID) N_PASSENGERS,
               SUM(SURVIVED) N_SURVIVED,
               SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
	  FROM MYDATA.DATASET4
	 GROUP BY 1, 2
	HAVING SEX='female') B
    ON A.AGEBAND=B.AGEBAND
 ORDER BY A.AGEBAND;
# 전반적으로 여성의 경우 모든 연령대에서 60% 이상의 생존율을 보임
# 반대로 남성의 경우 10,20대의 생존율이 50,60대와 비슷하게 나타남

#  3) Pclass(객실 등급)
SELECT PCLASS,
       COUNT(PASSENGERID) N_PASSENGERS,
       SUM(SURVIVED) N_SURVIVED,
       SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
  FROM MYDATA.DATASET4
 GROUP BY PCLASS
 ORDER BY 1;
# 생존율은 1등급, 2등급, 3등급 순으로 높게 나타남

# 객실 등급과 연령, 성별을 조합해 생존율 알아보기
SELECT PCLASS,
       SEX,
       COUNT(PASSENGERID) N_PASSENGERS,
       SUM(SURVIVED) N_SURVIVED,
       SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
  FROM MYDATA.DATASET4
 GROUP BY PCLASS, SEX
 ORDER BY 2, 1;
# 여성의 생존율이 높게 나타남
# 3등석 여성의 생존율이 1등석 남성의 생존율보다 높은 것은 실제로 객실 등급보다 연령, 성별이 구조에서 우선 고려된 것으로 보임

SELECT PCLASS,
       SEX,
       FLOOR(AGE/10)*10 AGEBAND,
       COUNT(PASSENGERID) N_PASSENGERS,
       SUM(SURVIVED) N_SURVIVED,
       SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
  FROM MYDATA.DATASET4
 GROUP BY PCLASS, SEX, FLOOR(AGE/10)*10
 ORDER BY 2, 1;
# 유아일수록 생존율이 높고, 모든 객실 등급에서 여성의 생존율이 더 높게 나타남

# 2. EMBARKED
# 승선 항구에 따른 승선자 수와 생존율의 관계 살펴보기
#  1) 승선 항구별 승객 수
SELECT EMBARKED,
       COUNT(PASSENGERID) N_PASSENGERS
  FROM MYDATA.DATASET4
 GROUP BY 1
 ORDER BY 1;
 
#  2) 승선 항구별, 성별 승객 수
SELECT EMBARKED,
       SEX,
       COUNT(PASSENGERID) N_PASSENGERS
  FROM MYDATA.DATASET4
 GROUP BY 1, 2
 ORDER BY 1, 2;
 
#  3) 승선 항구별, 성별 승객 비중(%)
#    A) 승선 항구별 전체 승객 수
SELECT EMBARKED,
       COUNT(PASSENGERID) N_PASSENGERS
  FROM MYDATA.DATASET4
 GROUP BY 1;
 
#    B) 승선 항구별, 성별 승객 수
SELECT EMBARKED,
       SEX,
       COUNT(PASSENGERID) N_PASSENGERS
  FROM MYDATA.DATASET4
 GROUP BY 1, 2;
 
#    C) 테이블 결합
SELECT A.EMBARKED,
       A.SEX,
       A.N_PASSENGERS,
       B.N_PASSENGERS N_PASSENGERS_TOT,
       A.N_PASSENGERS/B.N_PASSENGERS PASSENGERS_RAT
  FROM (SELECT EMBARKED,
               SEX,
               COUNT(PASSENGERID) N_PASSENGERS
	  FROM MYDATA.DATASET4
	 GROUP BY 1, 2) A
  LEFT
  JOIN (SELECT EMBARKED,
               COUNT(PASSENGERID) N_PASSENGERS
	  FROM MYDATA.DATASET4
	 GROUP BY 1) B
    ON A.EMBARKED = B.EMBARKED;
    
# 3. 탑승객 분석
#  1) 출발지, 도착지별 승객 수
SELECT BOARDED,
       DESTINATION,
       COUNT(PASSENGERID) N_PASSENGERS
  FROM MYDATA.DATASET4
 GROUP BY BOARDED,
          DESTINATION
 ORDER BY 3 DESC;
# Southampton에서 탑승해 New York City으로 향하는 승객이 가장 많음

# 상위 5개 경로를 선택한 승객들의 이름 추출하기
# 탑승객 수로 순위 매기기
SELECT *,
       ROW_NUMBER() OVER(ORDER BY N_PASSENGERS DESC) RNK
  FROM (SELECT BOARDED,
               DESTINATION,
               COUNT(PASSENGERID) N_PASSENGERS
          FROM MYDATA.DATASET4
         GROUP BY BOARDED,
                  DESTINATION) BASE;
				
# 상위 5개 경로 선택 후 해당 경로를 테이블로 생성하기
CREATE TEMPORARY TABLE MYDATA.ROUTE AS
SELECT BOARDED,
       DESTINATION
  FROM (SELECT *,
	       ROW_NUMBER() OVER(ORDER BY N_PASSENGERS DESC) RNK
	  FROM (SELECT BOARDED,
                       DESTINATION,
                       COUNT(PASSENGERID) N_PASSENGERS
		  FROM MYDATA.DATASET4
		 GROUP BY BOARDED, DESTINATION) BASE
	) BASE
 WHERE RNK BETWEEN 1 AND 5;
 
# 생성한 경로에 해당하는 승객들의 이름 추출하기
SELECT NAME_WIKI,
       A.BOARDED,
       A.DESTINATION
  FROM MYDATA.DATASET4 A
 INNER
  JOIN MYDATA.ROUTE B
    ON A.BOARDED = B.BOARDED AND A.DESTINATION = B.DESTINATION;
    
#  2) Hometown별 탑승객 수 및 생존율
SELECT HOMETOWN,
       SUM(1) N_PASSENGERS,
       SUM(SURVIVED)/SUM(1) SURVIVED_RATIO
  FROM MYDATA.DATASET4
 GROUP BY 1;
 
# 탑승객 수가 10명 이상이면서 생존율이 0.5이상인 HOMETOWN 알아보기
SELECT HOMETOWN,
       SUM(1) N_PASSENGERS,
       SUM(SURVIVED)/SUM(1) SURVIVED_RATIO
  FROM MYDATA.DATASET4
 GROUP BY 1
HAVING SUM(SURVIVED)/SUM(1)>=0.5 AND SUM(1)>=10;
