# CLASSICMODELS.ORDERDETAILS의 PRICEEACH가 30에서 50 사이인 데이터 조회
SELECT *
  FROM CLASSICMODELS.ORDERDETAILS
 WHERE PRICEEACH BETWEEN 30 AND 50; 
 
 # CLASSICMODELS.ORDERDETAILS의 PRICEEACH가 30이상인 데이터 조회
 SELECT *
   FROM CLASSICMODELS.ORDERDETAILS
  WHERE PRICEEACH>=30;

# CLASSICMODELS.CUSTOMERS가 USA 또는 CANADA인 CUSTOMERNUMBER 조회
SELECT CUSTOMERNUMBER
  FROM CLASSICMODELS.CUSTOMERS
 WHERE COUNTRY IN ('USA', 'CANADA');
 
 # CLASSICMODELS.CUSTOMERS가 USA, CANADA가 아닌 CUSTOMERNUMBER 조회
SELECT CUSTOMERNUMBER
  FROM CLASSICMODELS.CUSTOMERS
 WHERE COUNTRY NOT IN ('USA', 'CANADA');
 
 # CLASSICMODELS.EMPLOYEES의 REPORTSTO값이 NULL인 EMPLOYEENUMBER 조회
 SELECT EMPLOYEENUMBER
   FROM CLASSICMODELS.EMPLOYEES
  WHERE REPORTSTO IS NULL;
  
# CLASSICMODELS.EMPLOYEES의 REPORTSTO값이 NULL이 아닌 EMPLOYEENUMBER 조회
 SELECT EMPLOYEENUMBER
   FROM CLASSICMODELS.EMPLOYEES
  WHERE REPORTSTO IS NOT NULL;

# CLASSICMODELS.CUSTOMERS의 ADDRESSLINE1에 'ST'가 포함된 ADDRESSLINE1 출력
SELECT ADDRESSLINE1
  FROM CLASSICMODELS.CUSTOMERS
 WHERE ADDRESSLINE1 LIKE '%ST%';